project:
  type: website

website:
  title: "GISProject"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
    left:
      - href: intro.qmd
        text: Introduction
      - href: methodology.qmd
        text: Methodology
      - href: analysis.qmd
        text: Analysis
      - href: findings.qmd
        text: Results and Discussion

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

