---
title: "Conclusion"
editor: visual
---

# Future Work

## Extending Public Transport Accessibility Analysis to include Bus Networks 

For our project, we focused on walking accessibility for primary school students, as well as MRT and driving accessibility for secondary school and JC students. However, there is still a significant proportion of students who take public buses to school. Some students may also use a combination of MRT and bus to travel to school. Hence, a future extension of our work could include using bus networks to conduct network accessibility analysis. This would allow us to gain a more comprehensive analysis of accessibility to schools by public transport.

## In-depth Accessibility Analysis on Lower and Middle Income Areas

Equity of access to education is an important aspect of our project. To conduct more in-depth analysis, future work would include obtaining data of the average income for the different subzones and housing estates in Singapore, which would help us identify which areas house the lower and middle income population. Accessibility to schools in these areas would be even more crucial, as residents are more likely to be reliant on transportation modes such as walking and public transport. It would also be interesting to compare the accessibility to primary schools within 1km in areas with high income and areas with lower/middle income, as this allows residents to have priority admission when balloting. We would be able to gain meaningful insights with regards to whether higher income residents are in closer proximity to primary schools, resulting in inequity of access to education. 

## Accessibility Analysis on New Public Housing Estates

Another important area of future work would be accessibility analysis on new and upcoming public housing estates, such as Tengah and the Greater Southern Waterfront. While we conducted a brief driving and walking accessibility analysis for Tengah, we could extend the analysis to include other upcoming housing estates as well. The government has been launching many new Build-to-Order (BTO) Housing Development Board flats, aimed at young couples to buy their first home. Conducting accessibility analysis to schools in these areas would help potential home buyers assess the suitability of the different housing estates according to their needs. For example, most young couples would stay in their new BTO flat for at least five years, and would be looking at potential primary schools in the area. In the long term, they would be looking at secondary schools and JCs as well. Accessibility to education would be an important factor in home buyers\' decisions, influencing the attractiveness of the housing estate. 

# Lessons Learned

Through the GIS project experience in analysing the impact of mergers of education institutions on equity of access, our group gained a better understanding of the challenges of urban planning and the role of GIS in aiding the urban planning process. 

Changing demographics and declining enrolment have led to insufficient class sizes in Singapore educational institutions. Mergers of schools have become necessary to ensure that students across Singapore continue to benefit from vibrant educational experiences. The decision of school mergers involves both **technical analysis and political thinking**, which requires consideration of several factors, including the demographic change, geographical proximity of the schools to be merged and suitability of the merger (MENA,2021). However, the merger of schools will inevitably lead to geographical inequality in accessing educational institutions for certain areas. For example, in our analysis, we discovered that with the merger of Jurong Junior College and Pioneer Junior College, accessibility to Junior Colleges in the Western region of Singapore experienced a drastic decrease. In particular, Jurong West Central, one of the areas with a high population of youth that form the demand for schools, was significantly impacted by the merger. While these two schools may have faced lower enrolment rates, it is crucial to consider other factors when deciding on mergers, such as the demographics of the population and the density of the school network. As such, the use of GIS concepts and tools learned from class has allowed us to utilize spatial thinking to visualize and analyze such impacts and geographical inequality, leading to actionable insights moving forward. 

Another important factor in analyzing the impact of merger of schools on accessibility is the transportation mode. Based on the literature review conducted, we discovered that the choice of transportation has a high correlation to geographic accessibility, since the selection of optimal paths and transportation mode is one of the critical issues for parents who send their children to school (Meena et al., 2022). Transportation cost is another concern for lower and middle-income group parents, which makes it even more important to have schools in close proximity to housing estates, especially via walking and public transport. Therefore, we have learnt that the analysis of accessibility requires an understanding of transportation patterns. In addition, parents and students tend to have different preferences when choosing the transportation mode for different types of schools. For example, walking is the primary mode of transport for primary school students, compared to public transport for secondary school and JC students. Thus, the common transportation mode for different types of schools - primary, secondary and JC, should be considered for conducting accurate and in-depth analysis. This is an important analysis strategy that directed us in the project, leading us to focus on the main mode of transportation for the accessibility analysis of each type of school. 

Moreover, in deciding to merge schools, we learned that a critical consideration is being responsive to **changing demographics and future community demands** (MENA,2021)**.** For example, some areas have upcoming school demands, such as Tengah. As a new upcoming housing estate comprising 42,000 homes with affordable prices, Tengah attracts young couples and families to move in. In the years to come, demand for schools would undoubtedly increase, making accessibility to schools increasingly important for residents in the area. However, there are currently no schools in Tengah, making accessibility to schools, both walking and driving, extremely poor. To increase the attractiveness of Tengah and attract home buyers, the government may wish to consider building schools in Tengah. By analysing accessibility of schools to residents in Tengah, we gained better insights into conducting GIS analysis from a long-term and future perspective, which is important for urban planning. 

#  References

Geographical Distribution & Transport. SingStat. (2021, June). Retrieved November 10, 2022, from <https://www.singstat.gov.sg/-/media/files/visualising_data/infographics/c2020/c2020-geographical-distribution-transport.pdf>

How distance affects priority admission for P1 registration. Ministry of Education . (n.d.). Retrieved October 26, 2022, from [https://www.moe.gov.sg/primary/p1-registration/distance#:\~:text=Priority%20admission%20is%20given%20in,outside%202km%20of%20the%20school ](https://www.moe.gov.sg/primary/p1-registration/distance#:~:text=Priority%20admission%20is%20given%20in,outside%202km%20of%20the%20school )

Meena, D.K., Tripathi, R. & Agrawal, S. An evaluation of primary schools and its accessibility using GIS techniques: a case study of Prayagraj district, India. GeoJournal (2022). <https://doi.org/10.1007/s10708-022-10715-3>

Names of Primary and Secondary Schools Merging in 2019. (2017, December 29). Ministry of Education. Retrieved October 27, 2022, from <https://www.moe.gov.sg/news/press-releases/20171229-names-of-primary-and-secondary-schools-merging-in-2019.>

Singapore : School Mergers. (2021, Apr 09). MENA Report <http://libproxy.smu.edu.sg/login?url=https://www.proquest.com/wire-feeds/singapore-school-mergers/docview/2510495881/se-2>

Tengah Districts. HDB. (n.d.). Retrieved November 3, 2022, from <https://www.hdb.gov.sg/cs/infoweb/about-us/history/hdb-towns-your-home/tengah/tengah-districts>

Tengah's Park District to feature Singapore's first 'car-free' town centre, flats to be launched in August. CNA. (2020, August 10). Retrieved November 3, 2022, from <https://www.channelnewsasia.com/singapore/hdb-tengah-park-district-flats-car-free-town-centre-615171>

Wong, J. (2022, November 17). November 2022 HDB BTO Review -- Tengah. 99.co property website singapore. Retrieved November 3, 2022, from <https://www.99.co/singapore/insider/november-2022-hdb-bto-review-tengah/>

\




\

