---
title: "Introduction"
editor: visual
---

## Overview

Our project \_\_\_\_\_\_\_\_\_, aims to find the impact of closures or mergers of primary schools on the equity of access to primary school education in Singapore.

Our group chose to tackle this problem due to the competitiveness in primary school enrollment for schools in nearby neighborhoods. Since 2017, MOE started announcing school mergers and closures in waves every year, in order to improve ["the quality of the school experience"](https://www.gov.sg/article/why-is-the-ministry-of-education-merging-some-schools) due to declining birth rates leading to low-enrolment schools with insufficient class sizes. By merging these schools, MOE wants to maintain class sizes so schools can offer wider ranges of subjects, CCAs and programmes. Our group's objective is to find if these school mergers and closures have resulted in certain estates and subzones getting left behind in terms of access to nearby schools as their schools have been shut down.

## Project Tasks

The project tasks are as follows:

-   To compile the necessary data:

    -   Singapore road network

-   To derive new data sets:

    -   Lists of Primary Schools and their Postal Codes before and after school mergers, closures and relocations

    -   List of Singapore subzones affected by school closures

-   To perform Network Analysis on the locations of primary schools in Singapore before and after closures to find areas in Singapore disproportionately far away from primary schools after the change.

-   To provide recommendations on new schools or new estate locations based on our findings

## The Data

The following data sets will be used:

1.  Singapore School Locations from [geo.sg](https://geo.sg/gmaps/singapore-schools/show_data)

2.  Listing of all school location changes in Singapore from 2010 - [elite.com.sg](https://elite.com.sg/school-change)

3.  Road data from Open Street Maps downloaded from [GeoFabrik](https://download.geofabrik.de/asia/malaysia-singapore-brunei.html)

4.  Master Plan 2019 Subzone Boundary (No Sea) from [Data.gov.sg](https://data.gov.sg/dataset/master-plan-2019-subzone-boundary-no-sea)
